apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: kabanero-catalog
  namespace: openshift-marketplace
  labels:
    kabanero.io/install: 00-catalogsource
spec:
  sourceType: grpc
  image: kaczyns/kabanero-operator-registry:tekton-triggers
  publisher: kabanero.io
  displayName: Kabanero Operators
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: elasticsearch-operator
  namespace: openshift-operators
  labels:
    kabanero.io/install: 10-subscription
spec:
  channel: "4.2"
  installPlanApproval: Automatic
  name: elasticsearch-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: jaeger-product
  namespace: openshift-operators
  labels:
    kabanero.io/install: 10-subscription
spec:
  channel: stable
  installPlanApproval: Automatic
  name: jaeger-product
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kiali-ossm
  namespace: openshift-operators
  labels:
    kabanero.io/install: 10-subscription
spec:
  channel: stable
  installPlanApproval: Automatic
  name: kiali-ossm
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: servicemeshoperator
  namespace: openshift-operators
  labels:
    kabanero.io/install: 11-subscription
spec:
  channel: kabanero-0.4
  installPlanApproval: Automatic
  name: servicemeshoperator
  source: kabanero-catalog
  sourceNamespace: openshift-marketplace
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: knative-eventing-operator
  namespace: openshift-operators
  labels:
    kabanero.io/install: 12-subscription
spec:
  channel: kabanero-0.4
  config:
    resources: {}
  installPlanApproval: Automatic
  name: knative-eventing-operator
  source: kabanero-catalog
  sourceNamespace: openshift-marketplace
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: serverless-operator
  namespace: openshift-operators
  labels:
    kabanero.io/install: 12-subscription
spec:
  channel: kabanero-0.5
  installPlanApproval: Automatic
  name: serverless-operator
  source: kabanero-catalog
  sourceNamespace: openshift-marketplace
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-pipelines
  namespace: openshift-operators
  labels:
    kabanero.io/install: 13-subscription
spec:
  channel: kabanero-0.5
  config:
    resources: {}
  installPlanApproval: Automatic
  name: openshift-pipelines-operator
  source: kabanero-catalog
  sourceNamespace: openshift-marketplace
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: appsody-operator-certified
  namespace: openshift-operators
  labels:
    kabanero.io/install: 13-subscription
spec:
  channel: kabanero-0.5
  config:
    resources: {}
  installPlanApproval: Automatic
  name: appsody-operator-certified
  source: kabanero-catalog
  sourceNamespace: openshift-marketplace
---
apiVersion: v1
kind: Namespace
metadata:
  name: kabanero
  labels:
    kabanero.io/install: 14-subscription
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: kabanero
  namespace: kabanero
  labels:
    kabanero.io/install: 14-subscription
spec:
  targetNamespaces:
  - kabanero
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: eclipse-che
  namespace: kabanero
  labels:
    kabanero.io/install: 14-subscription
spec:
  channel: kabanero-0.4
  installPlanApproval: Automatic
  name: eclipse-che
  source: kabanero-catalog
  sourceNamespace: openshift-marketplace
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kabanero-operator
  namespace: kabanero
  labels:
    kabanero.io/install: 14-subscription
spec:
  channel: release-0.5
  installPlanApproval: Automatic
  name: kabanero-operator
  source: kabanero-catalog
  sourceNamespace: openshift-marketplace
---
