apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    kabanero.io/install: 20-cr-servicemeshcontrolplane
    kabanero.io/namespace: 'true'
---
apiVersion: maistra.io/v1
kind: ServiceMeshControlPlane
metadata:
  name: basic-install
  namespace: istio-system
  labels:
    kabanero.io/install: 20-cr-servicemeshcontrolplane
spec:
  istio:
    global:
      disablePolicyChecks: false
    gateways:
      istio-ingressgateway:
        autoscaleEnabled: false
      istio-egressgateway:
        enabled: false
    mixer:
      enabled: false
    pilot:
      autoscaleEnabled: false
    kiali:
      enabled: false
    tracing:
      enabled: false
    prometheus:
      enabled: false
    grafana:
      enabled: false
---
apiVersion: maistra.io/v1
kind: ServiceMeshMemberRoll
metadata:
  name: default
  namespace: istio-system
  labels:
    kabanero.io/install: 21-cr-servicemeshmemberrole
spec:
  members:
  - knative-serving
  - tekton-pipelines
  - kabanero
---
apiVersion: v1
kind: Namespace
metadata:
  name: knative-serving
  labels:
    kabanero.io/install: 22-cr-knative-serving
    kabanero.io/namespace: 'true'
---
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
  labels:
    kabanero.io/install: 22-cr-knative-serving
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all
  namespace: kabanero
  labels:
    kabanero.io/install: 23-cr-network-policy
spec:
  podSelector: {}
  ingress:
  - {}
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all
  namespace: tekton-pipelines
  labels:
    kabanero.io/install: 23-cr-network-policy
spec:
  podSelector: {}
  ingress:
  - {}
  policyTypes:
  - Ingress
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kabanero-pipeline
  namespace: kabanero
  labels:
    kabanero.io/install: 24-pipeline-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kabanero-pipeline-role 
  namespace: kabanero
  labels:
    kabanero.io/install: 24-pipeline-sa  
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - use
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  - services
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - pods/log
  - namespaces
  - events
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  verbs:
  - get
  - list
  - create
  - delete
  - update
  - watch
- apiGroups:
  - extensions
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
- apiGroups:
  - tekton.dev
  resources:
  - tasks
  - clustertasks
  - taskruns
  - pipelines
  - pipelineruns
  - pipelineresources
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
- apiGroups:
  - tekton.dev
  resources:
  - taskruns/finalizers
  - pipelineruns/finalizers
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
- apiGroups:
  - tekton.dev
  resources:
  - tasks/status
  - clustertasks/status
  - taskruns/status
  - pipelines/status
  - pipelineruns/status
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
- apiGroups:
  - kabanero.io
  resources:
  - stacks
  - kabaneros
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
- apiGroups:
  - ""
  - image.openshift.io
  resources:
  - imagestreams/layers
  verbs:
  - get
  - update
- apiGroups:
  - ""
  - image.openshift.io
  resources:
  - imagestreams
  verbs:
  - create
- apiGroups:
  - config.openshift.io
  resources:
  - images
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ''
  - image.openshift.io
  resources:
    - imagesignatures
  verbs:
    - create
    - delete
- nonResourceURLs:
  - '/staging/*'
  verbs:
    - get
    - put
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kabanero-pipeline-cluster-role-binding
  labels:
    kabanero.io/install: 24-pipeline-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kabanero-pipeline-role
subjects:
- kind: ServiceAccount
  name: kabanero-pipeline
  namespace: kabanero
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kabanero-pipeline-deploy-role 
  namespace: kabanero
  labels:
    kabanero.io/install: 24-pipeline-sa  
rules:
- apiGroups:
  - appsody.dev
  resources:
  - appsodyapplications
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
- apiGroups:
  - openliberty.io
  resources:
  - openlibertyapplications
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
- apiGroups:
  -  apps.openshift.io
  resources:
  - serviceBindingRequests
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
- apiGroups:
  -  kafka.strimzi.io
  resources:
  - kafka
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - serviceMonitor
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
- apiGroups:
  - postgresql.baiju.dev
  resources:
  - database
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kabanero-trigger-role 
  namespace: tekton-pipelines
  labels:
    kabanero.io/install: 25-triggers-role
rules:
- apiGroups:
  - tekton.dev
  - triggers.tekton.dev
  resources:
  - triggerbindings
  - triggertemplates
  - eventlisteners
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: event-listener
  namespace: kabanero
  labels:
    kabanero.io/install: 26-events-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: event-listener-role 
  namespace: kabanero
  labels:
    kabanero.io/install: 26-events-sa 
rules:
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - get
  - list
  - create
  - delete
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  - services
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - pods/log
  - namespaces
  - events
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  verbs:
  - get
  - list
  - create
  - delete
  - update
  - watch
- apiGroups:
  - extensions
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
- apiGroups:
  - tekton.dev
  resources:
  - tasks
  - clustertasks
  - taskruns
  - pipelines
  - pipelineruns
  - pipelineresources
  - conditions
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
- apiGroups:
  - triggers.tekton.dev
  resources:
  - eventlisteners
  - triggerbindings
  - triggertemplates
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
- apiGroups:
  - tekton.dev
  resources:
  - taskruns/finalizers
  - pipelineruns/finalizers
  - tasks/status
  - clustertasks/status
  - taskruns/status
  - pipelines/status
  - pipelineruns/status
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: event-listener-role-binding
  namespace: kabanero
  labels:
    kabanero.io/install: 26-events-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: event-listener-role
subjects:
- kind: ServiceAccount
  name: event-listener
  namespace: kabanero
