apiVersion: apps/v1
kind: Deployment
metadata:
  name: kabanero-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kabanero-operator
  template:
    metadata:
      labels:
        name: kabanero-operator
    spec:
      serviceAccountName: kabanero-operator
      containers:
        - name: kabanero-operator
          # Replace this with the built image name
          image: quay.io/kyleschlosser/kabanero-operator
          command:
          - kabanero-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "kabanero-operator"
