# This file contains optional components of Kabanero.  Each object for
# an optional component is labeled with kabanero.io/component, with
# the value being the component name.  The optional components are
# then applied using a selector.  For example:
#   kubectl apply -f optional.yaml --selector=kabanero.io/component=kappnav
#

# -----------------------------------------------------------------------
# KAppNav 0.5.0
# -----------------------------------------------------------------------
apiVersion: v1
kind: Namespace
metadata:
  name: kappnav
  labels:
    kabanero.io/component: kappnav
---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kappnavs.kappnav.operator.kappnav.io
  labels:
    kabanero.io/component: kappnav
spec:
  group: kappnav.operator.kappnav.io
  names:
    kind: Kappnav
    listKind: KappnavList
    plural: kappnavs
    singular: kappnav
  scope: Namespaced
  subresources:
    status: {}
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: kappnav-operator
  namespace: kappnav
  labels:
    kabanero.io/component: kappnav
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kappnav-operator
  labels:
    kabanero.io/component: kappnav
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kappnav-operator
  labels:
    kabanero.io/component: kappnav
subjects:
- kind: ServiceAccount
  name: kappnav-operator
  namespace: kappnav
roleRef:
  kind: ClusterRole
  name: kappnav-operator
  apiGroup: rbac.authorization.k8s.io
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kappnav-operator
  namespace: kappnav
  labels:
    kabanero.io/component: kappnav
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kappnav-operator
  template:
    metadata:
      labels:
        name: kappnav-operator
    spec:
      serviceAccountName: kappnav-operator
      containers:
        - name: kappnav-operator
          # Replace this with the built image name
          image: kappnav/operator:0.5.0
          command:
          - kappnav-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "kappnav-operator"
---

apiVersion: kappnav.operator.kappnav.io/v1
kind: Kappnav
metadata:
  name: kappnav
  namespace: kappnav
  labels:
    kabanero.io/component: kappnav
spec:
  # Default values copied from <project_dir>/helm-charts/kappnav/values.yaml

  ###############################################################################
  ## kAppNav REST API variables
  ###############################################################################

  appNavAPI:
    repository: kappnav/apis
    tag: 0.5.0

  ###############################################################################
  ## kAppNav Controller variables
  ###############################################################################

  appNavController:
    repository: kappnav/controller
    tag: 0.5.0

  ###############################################################################
  ## kAppNav UI variables
  ###############################################################################

  appNavUI:
    repository: kappnav/ui
    tag: 0.5.0

  ###############################################################################
  ## Environmental variables
  ###############################################################################
  env:
    kubeEnv: ocp
