# This example demonstrates all of the possible configuration elements
#
# Note that some of the attributes may not make sense in combination with other attributes
# and that this sample might not be runable as-is
apiVersion: kabanero.io/v1alpha2
kind: Kabanero
metadata:
  name: kabanero
spec:
  # The platform version determines the desired version for all components, but those
  # can be overriden individually as well
  version: "0.9.1"

  targetNamespaces:
  - kabanero

  cliServices:
    # Overrides the setting for version on this component
    version: "0.9.1"

    # Overrides the image as a separate repository or tag
    repository: kabanero/kabanero-command-line-services
    tag: "0.9.1-rc.2"

    # Overrides the image uri
    image: kabanero/kabanero-command-line-services:0.9.1-rc.2

    # Indicates the token expiration time 
    # Specify a positive integer followed by a unit of time, which can be hours (h), minutes (m), or seconds (s). 
    # For example, specify 30 seconds as 30s. 
    # You can include multiple values in a single entry. For example, 1m30s is equivalent to 90 seconds.
    sessionExpirationSeconds: "1440m"

  collectionController:
    # Overrides the setting for version on this component
    version: "0.9.1"

    # Overrides the image as a separate repository or tag
    repository: kabanero/kabanero-operator
    tag: "TRAVIS_TAG"

    # Overrides the image uri
    image: kabanero/kabanero-operator:TRAVIS_TAG

  stackController:
    # Overrides the setting for version on this component
    version: "0.9.1"

    # Overrides the image as a separate repository or tag
    repository: kabanero/kabanero-operator
    tag: "TRAVIS_TAG"

    # Overrides the image uri
    image: kabanero/kabanero-operator:TRAVIS_TAG

  landing:
    # The landing page is enabled by default. To disable specify false.
    enable: true

    # Overrides the setting for version on this component
    version: "0.9.0"

    # Overrides the image as a separate repository or tag
    repository: kabanero/landing
    tag: "0.9.0"

    # Overrides the image uri
    image: kabanero/landing:0.9.0

  admissionControllerWebhook:
    # Overrides the setting for version on this component
    version: "0.9.1"

    # Overrides the image as a separate repository or tag
    repository: kabanero/kabanero-operator
    tag: "TRAVIS_TAG"

    # Overrides the image uri
    image: kabanero/kabanero-operator:TRAVIS_TAG
    
  codeReadyWorkspaces:
    # CodeReadyWorkspaces CR instance deployment is disabled by default. To enable it, set the enable value to true. 
    enable: true

    operator:
      # Custom resource instance configuration.
      customResourceInstance:
        # Image used in Devfile registry deployment.
        devFileRegistryImage:
          # Overrides the setting for version on this component.
          version: "0.9.0"

          # Overrides the image as a separate repository or tag
          repository: kabanero/che-devfile-registry
          tag: "0.11.0"

          # Overrides the image uri
          image: kabanero/che-devfile-registry:0.11.0

        # Specifies a custom cluster role to user for the Che workspaces uses the default roles if left blank.
        # The default value is kabanero-codewind.
        cheWorkspaceClusterRole: kabanero-codewind

        # TLS mode for Che. Make sure you either have public cert, or set selfSignedCert to true. The default value is false.
        tlsSupport: false

        # When set to true the operator will attempt to get a secret in OpenShift router namespace to add it to Java
        # trust store of Che server. Requires cluster-admin privileges for operator service account. The default value is false.
        selfSignedCert: false

        # Instructs an Operator to enable OpenShift v3 identity provider in Keycloak, as well as create respective
        # oAuthClient and configure Che configMap accordingly. The default value is false.
        openShiftOAuth: false

  stacks:
    # A list of those repositories which are searched for stacks
    repositories: 
    - name: incubator
      https:
        url: https://github.com/kabanero-io/kabanero-stack-hub/releases/download/0.9.0/kabanero-stack-hub-index.yaml
    pipelines:
    - id: default
      sha256: 61281610991b7e21ed64b97cba0fbd15e1647b48cc9e3eb5e66474519aed4f7b
      https:
        url: https://github.com/kabanero-io/kabanero-pipelines/releases/download/0.9.1-rc.3/default-kabanero-pipelines.tar.gz

  gitops:
    pipelines:
    - id: gitops
      sha256: ffb2df99b5e4cfb3e634afd4f0d851cb43d039e52ed5e0866fd4ffac41b288e8
      https:
        url: https://github.com/kabanero-io/kabanero-pipelines/releases/download/0.9.1-rc.3/kabanero-gitops-pipelines.tar.gz

  governancePolicy:
    # Provide governance configuration for all stacks managed by Kabanero. The allowed configuration policies are:
    # strictDigest, activeDigest, ignoreDigest, and none. If a stack policy is not specified, activeDigest is used. 
    stackPolicy: activeDigest

  # The information in the 'github' section is used by the Kabanero CLI and Console to
  # help access and manage the stacks.
  github:
    # The API URL refers to the GitHub instance (or GHE instance) that
    # contains the organization where the stack hub was forked.  The
    # CLI will use this URL to interact with GitHub (or GHE).
    apiUrl: https://api.github.com
    # The GitHub organization contains the repository where the
    # stack hub was forked.
    organization: kabanero-io
    # The list of teams which should have admin authority to the
    # stack.  Each team must be defined in the GitHub
    # organization.  Members of the teams will be able to login to the
    # Kabanero CLI and Console to administer the stack.
    teams:
    - adminTeam

  # Kabanero events operator configuration
  events:
    # The events operator is enabled by default.  It can be disabled
    # by setting `enable` to `false`.
    enable: true

    # Overrides the version of the events operator, as defined in
    # config/versions.yaml
    version: "0.9.0"

    # Overrides the events-operator image as a separate repository or tag
    repository: kabanero/events-operator
    tag: "0.1.0"

    # Overrides the events-operator image uri
    image: kabanero/events-operator:0.1.0

  # Single Sign-on
  sso:
    adminSecretName: rhsso-secret
    enable: false
