apiVersion: kabanero.io/v1alpha1
kind: Kabanero
metadata:
  name: kabanero
spec:
  # The platform version determines the desired version for all components, but those
  # can be overriden individually as well
  version: 0.0.1

  collections: 
    # Installs a default set of collections
    enableFeatured: true

    # A list of those repositories which are searched for collections
    repositories: 
    - name: experimental
      url: https://github.com/kabanero-io/kabanero-collection/blob/master/experimental
