# This example demonstrates all of the possible configuration elements
#
# Note that some of the attributes may not make sense in combination with other attributes
# and that this sample might not be runable as-is
apiVersion: kabanero.io/v1alpha2
kind: Kabanero
metadata:
  name: kabanero
spec:
  # The platform version determines the desired version for all components, but those
  # can be overriden individually as well
  version: "0.6.0"

  targetNamespaces:
  - ns1
  - ns2

  cliServices:
    # Overrides the setting for version on this component
    version: "0.6.0"

    # Overrides the image as a separate repository or tag
    repository: kabanero/kabanero-command-line-services
    tag: "0.6.0-rc.4"

    # Overrides the image uri
    image: kabanero/kabanero-command-line-services:0.6.0-rc.4

    # Indicates the token expiration time 
    # Specify a positive integer followed by a unit of time, which can be hours (h), minutes (m), or seconds (s). 
    # For example, specify 30 seconds as 30s. 
    # You can include multiple values in a single entry. For example, 1m30s is equivalent to 90 seconds.
    sessionExpirationSeconds: "1440m"

  collectionController:
    # Overrides the setting for version on this component
    version: "0.6.0-rc.2"

    # Overrides the image as a separate repository or tag
    repository: kabanero/kabaner-operator-collection-controller
    tag: "0.6.0-rc.2"

    # Overrides the image uri
    image: kabanero/kabanero-operator-collection-controller:0.6.0-rc.2

  stackController:
    # Overrides the setting for version on this component
    version: "0.6.0-rc.2"

    # Overrides the image as a separate repository or tag
    repository: kabanero/kabaner-operator-stack-controller
    tag: "0.6.0-rc.2"

    # Overrides the image uri
    image: kabanero/kabanero-operator-stack-controller:0.6.0-rc.2

  landing:
    # The landing page is enabled by default. To disable specify false.
    enable: true

  admissionControllerWebhook:
    # Overrides the setting for version on this component
    version: "0.6.0-rc.2"

    # Overrides the image as a separate repository or tag
    repository: kabanero/kabanero-operator-admission-webhook
    tag: "0.6.0-rc.2"

    # Overrides the image uri
    image: kabanero/kabanero-operator-admission-webhook:0.6.0-rc.2
    
  codeReadyWorkspaces:
    # CodeReadyWorkspaces CR instance deployment is disabled by default. To enable it, set the enable value to true. 
    enable: true

    operator:
      # Custom resource instance configuration.
      customResourceInstance:
        # Image used in Devfile registry deployment.
        devFileRegistryImage:
          # Overrides the setting for version on this component.
          version: "0.6.0"

          # Overrides the image as a separate repository or tag
          repository: kabanero/che-devfile-registry
          tag: "0.8.0"

          # Overrides the image uri
          image: kabanero/che-devfile-registry:0.8.0

        # Specifies a custom cluster role to user for the Che workspaces uses the default roles if left blank.
        # The default value is eclipse-codewind.
        cheWorkspaceClusterRole: eclipse-codewind

        # TLS mode for Che. Make sure you either have public cert, or set selfSignedCert to true. The default value is false.
        tlsSupport: false

        # When set to true the operator will attempt to get a secret in OpenShift router namespace to add it to Java
        # trust store of Che server. Requires cluster-admin privileges for operator service account. The default value is false.
        selfSignedCert: false

        # Instructs an Operator to enable OpenShift v3 identity provider in Keycloak, as well as create respective
        # oAuthClient and configure Che configMap accordingly. The default value is false.
        openShiftOAuth: false

  stacks:
    # A list of those repositories which are searched for collections
    repositories: 
    - name: incubator
      https:
        url: https://github.com/kabanero-io/collections/releases/download/0.6.0-rc.1/kabanero-index.yaml
    pipelines:
    - id: default
      sha256: 6eb598555a6b0c1d0a7e1a215343145f83cea70820eb99f60ee67f3d3201e441
      https:
        url: https://github.com/kabanero-io/kabanero-pipelines/releases/download/0.6.0-rc2/default-kabanero-pipelines.tar.gz

  # The information in the Github section is used by the Kabanero CLI to
  # perform user to role mapping when accessing the collection.
  github:
    # The API URL refers to the Github instance (or GHE instance) that
    # contains the organization where the collection was cloned.  The
    # CLI will use this URL to interact with Github (or GHE).
    apiUrl: https://api.github.com
    # The Github organization contains the repository where the
    # collection was cloned.
    organization: kabanero-io
    # The list of teams which should have admin authority to the
    # collection.  Each team must be defined in the Github
    # organization.  Members of the teams will be able to login to the
    # Kabanero CLI and administer the collection.
    teams:
    - adminTeam
