packageName: serverless-operator
channels:
- name: kabanero-0.3
  currentCSV: serverless-operator.v1.1.0
- name: kabanero-0.4
  currentCSV: serverless-operator.v1.1.0
- name: kabanero-0.5
  currentCSV: serverless-operator.v1.2.0
- name: kabanero-0.6
  currentCSV: serverless-operator.v1.4.1
- name: kabanero-0.7
  currentCSV: serverless-operator.v1.4.1
defaultChannel: kabanero-0.7
